name: 'Python: Scylla'

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python-version: [ 3.9 ]

    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/playwright-github-action@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        make install-dependencies-ubuntu
        pip install -r tests/requirements-test.txt
        pip install -e.
        python -m playwright install
    - name: Lint with flake8
      run: |
        make style-check
    - name: Test with pytest
      run: |
        pytest --cov=./scylla tests